### ISSUE TITLE
Add HoneyPot

### ISSUE THREAD

**Issue by ArthurBrito** [AvantSD/gsd-form#11]
I would like to be able to config my form with or without Honeypot.

The honeypot is a simple field in the form with display none, that can't be reachable with tabs and can't be auto-completed. So basically only bots will change its values. If the value was changed, then we ignore the request.

I would like to use like that:
```
form: {
  honeypot: true,
  fields: {...}
}
```

**Comment by abdielbrilhante** [comment]
We're open to pull requests, you know.
